# Generated by Django 5.0.4 on 2024-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Описание')),
                ('img', models.TextField(verbose_name='Изображение')),
            ],
        ),
    ]
